Cargo.toml
build.rs
src/lib.rs

Utilizes R_HOME environment variable to determine R version to build against.

Added support to build against specific R versions

---

Cargo.toml
README.md
build.rs
src/lib.rs
wrapper.h

This works for me on OS X. I suspect it'll work on Linux and Windows as well, but haven't tested. Would be great if somebody else could.
Closes #6.

Remove pkg-config from build process

---

.github/workflows/test.yml
README.md
src/lib.rs

set up GH actions

---

.github/workflows/test.yml

Closes #41.
Renamed all steps in my fork to bypass possible caching to confirm it works.

Removing unnecessary MSYS2 step from GHA

---

CODE-OF-CONDUCT.md
CONTRIBUTING.md

I have created contributing guidelines and code of conduct. I envision that we could use these throughout the extendr project.
@andy-thomason @yutannihilation Could you review and let me know if you see any issues or have suggestions for additional items that should be mentioned?

Contributing guidelines and code of conduct

---

Cargo.toml
LICENSE

As discussed with @andy-thomason: Acknowledge two additional authors, @dasmoth and @CGMossa.
@dasmoth, @CGMossa: Please let me know if you would like to be acknowledged with your real name or your github user name and whether you want to list an email address, and if so what it is.
Thanks!

extend author list

---

CHANGELOG.md
build.rs

Output R version info

---

build.rs

Fix error message

---

README.md

Fixes #31 in preparation for #66.

Updating readme for Windows

---

bindings/bindings-linux-x86_64-R4.1.rs
wrapper.h

Address https://github.com/extendr/libR-sys/issues/66#issuecomment-882669880

Include R_ext/GraphicsEngine.h

---

CHANGELOG.md
Cargo.toml
README.md

- Increment the version number
- Update changelog
- Tweak README

Changes for releasing libR-sys 0.2.2

---

build.rs

Setting r version cargo vars correctly

---

CHANGELOG.md
Cargo.toml
README.md
build.rs

Remove winapi dependency

---

.github/workflows/test.yml
README.md

Close https://github.com/extendr/extendr/issues/442

Use Rtools43

---

Cargo.toml

https://github.com/extendr/extendr/issues/457

Use the 2021 edition

---

Cargo.toml

Cleaning up my name & email so it is the same across all extendr projects.

Fix initials & change email to consolidate contat info between repos

---

.github/workflows/test.yml

https://github.com/extendr/extendr/pull/479

Use ubuntu-latest on CI

---

.github/workflows/test.yml

Address https://github.com/extendr/extendr/issues/425
See https://github.com/extendr/extendr/pull/477 for the explanation about the changes.

Use dtolnay/rust-toolchain

---

wrapper.h

Add random number generator state wrappers

---

bindings/bindings-linux-aarch64.rs

Add bindings-linux-aarch64.rs

---

CHANGELOG.md
Cargo.toml

https://github.com/extendr/libR-sys/issues/115

Update the changelog and bump version for releasing v0.4.0

---

.github/workflows/doc.yml

Close https://github.com/extendr/extendr/issues/510

Generate index.html

---

CHANGELOG.md
build.rs

Address https://github.com/extendr/extendr/issues/580

Allow non-existent path of r_library

---

.github/workflows/doc.yml
.github/workflows/non-api-call.yml
.github/workflows/test.yml

Bump versions of  actions/checkout@v2 and actions/download-artifact@v2

---

build.rs

fix https://github.com/extendr/libR-sys/issues/222

fix build error for ubuntu: Problem locating local R install
