- Cargo.toml
- build.rs
(Also bumps version number to support forthcoming PR for extendr).
This should increase the chance of things running out-of-the-box on more platforms.  So far been tested on Fedora Linux + R4.0.2 and MacOS + homebrew + R3.5.
NB. I haven't fully removed the InstallationPaths stuff since it was clearly added for a reason, but this may need some rethinking since it makes assumptions about the relative location of libraries, pkg-config, etc., which are not true on all platforms (e.g. Fedora).
> Use pkg-config to get include path(s), and export R_HOME.

- Cargo.toml
- build.rs
- wrapper.h
This is a first step towards enabling conditional compilation in extendr for features from recent versions of R.
Work-in-progress extendr side of this is at https://github.com/dasmoth/extendr/commit/c9c9c0534ea2e5bb3053e4ad0a9357e977c8240f.  Current plan is to allow conditional features in the style of:
```rust
#[cfg(r_version_4_1)]
pub fn failure() {
// This is safe since 4.1 isn't out yet...
Rf_doesNotExist();
}
```
I'll send a pull request for that once I've had a chance to annotate affected methods on the extendr side.
> Expose R_VERSION number as metadata

- Cargo.toml
- build.rs
I have patched the build script to also save the bindings to a folder specified by `$LIBRSYS_BINDINGS_DIR`, if it is set. This makes it easy to generate and cache the bindings.
> enable easy extraction of created bindings

- build.rs
When `R_HOME` is set we should just use it rather than try to run R to find it. In fact, when R builds extension packages it explicitly disables running R without a complete path.
> use R_HOME if available

- build.rs
The reworked code only tries to find the top-level R folder and then assumes a standard directory structure underneath. This should fix some problems on Windows.
> Improved path setup

- bindings/bindings-linux-x86_64-R4.0.rs
- bindings/bindings-linux-x86_64.rs
- bindings/bindings-macos-x86_64-R4.0.rs
- bindings/bindings-macos-x86_64.rs
- bindings/bindings-windows-x86-R4.0.rs
- bindings/bindings-windows-x86.rs
- bindings/bindings-windows-x86_64-R4.0.rs
- bindings/bindings-windows-x86_64.rs
- wrapper.h
Make sure `R_xlen_t` is always mapped to `isize`, even on 32 bit. Closes #28.
> bindgen override for R_xlen_t. 

- README.md
Restructures section dedicated to building for  `Windows`.
Includes both `CMD` and `PowerShell` commands (where applicable).
Also, utilizes a feature available in `cargo` if installed via `rustup`:
`cargo +toolchain build --target=target` allows to build using `toolchain` without setting default toolchain, which is very important if we want to easily build for 32 and 64 bits.
> Updating Windows description in README

- Cargo.toml
- LICENSE
- bindings/bindings-windows-x86-R3.6.rs
- bindings/bindings-windows-x86-R4.0.rs
- bindings/bindings-windows-x86-R4.1-devel.rs
- build.rs
Addresses, but does not fully fix issue #39.
Enables bindgen layout test but blacklists two problematic types (for Win-x86) only.
New precomputed bindings with tests for Win-x86.
> Fixing i686 tests

- .github/workflows/test.yml
After discussing this issue in https://github.com/extendr/rextendr/issues/19, a solution was found to build & test `libR-sys` using only rtools. This does not work for bindings generation (no clang provided with rtools), but is suitable for user consumption.
Currently, rtools mingw64 should be "fixed" (see https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-gcc/PKGBUILD#L305-L309) by duplicating `libgcc.a` as `libgcc_eh.a`, which satisfies `rustc` and linker.
Build & test were reordered. 
First, rtools is configured and precomputed bindings are tested.
Second, msys2 is enabled and bindings generation is tested using msys2.
This does not affect other systems.
Partially addresses #21.
> Using rtools to test precomputed bindings on Windows

- Cargo.toml
- build.rs
Just happened to find this. winapi's README says:
> Should I still use those -sys crates such as kernel32-sys?
> 
> No. Those crates are a legacy of how winapi 0.2 was organized. Starting with winapi 0.3 all definitions are directly in winapi itself, and so there is no longer any need to use those -sys crates.
So I guess we only need to use winapi, right? (I didn't even know winapi is a successor of kernel32-sys until today...)
> Remove kernel32-sys

- .github/workflows/test.yml
- ci-cargo.ps1
In light of the new release of Rtools (Rtools40v2, see discussion here https://github.com/extendr/libR-sys/issues/21), which allows us to finally fix Rtools bindgen tests, I suggest to slightly improve the CI, reducing the amount of boilerplate.
This was previously done in `extendr` by introducing `ci-cargo.ps1` powershell script that handles `cargo` errors in a cross-platform manner. 
I took [`ci-cargo.ps1`](https://github.com/extendr/extendr/blob/master/ci-cargo.ps1) from `extendr` and replaced all boilerplate code with simple calls to `ci-cargo`.
> Using `ci-cargo` from `extendr`

- .github/workflows/test.yml
This fixes #53.
[Rtools40v2](https://cran.r-project.org/bin/windows/Rtools/) has been recently released.
It includes our [hack](https://github.com/r-windows/rtools-packages/pull/186) to please rust compiler and resolves `gcc` linking issue.
`libR-sys` can now be safely tested using Rtools only (no dependence on `msys2` is required for pre-computed bindings).
However, the `setup-r` [action](https://github.com/r-lib/actions) currently have a bug that does not allow installing other versions of Rtools40 even if the version string is explicitly specified (see my issue here https://github.com/r-lib/actions/issues/289).
There is also a PR to make the new version default (https://github.com/r-lib/actions/pull/287), which will not work until the issue is resolved.
I suggest to leave this PR as a …
> Using `Rtools40v2` to test bindings on Windows

- .github/workflows/test.yml
The document says:
> macOS 11 image label was changed to macos-11 to avoid confusion with the minor version.
<https://github.com/actions/virtual-environments/blob/main/docs/macos-11-onboarding.md>
but, reading the above documentation, maybe this isn't available to us until we apply for the feature? Let's see what will happen...
> Fix macos-11 runner

- .github/workflows/test.yml
- MAINTAINERS_GUIDE.md
Related to #57
This pull request adds a job to gather the uploaded generated bindings and commit them to `generated_bindings` branch. We can create a pull request from that branch at any point we want to update the bindings. Of course we can commit this to the master branch, but I feel this should be done manually with checking the diffs by our eyes, at least at the moment.
This does nothing if there's no diffs, and even if something goes wrong, this pushes to non-`master`, where no CI is set up. So, I believe this should be safe.
This pull request adds a scheduled run setting. I use this on https://github.com/ggplot2-exts/gallery for a while and it works fine.
@Ilia-Kosenkov @clauswilke 
Please let me know if there's any concern, or any topic to discuss.
> Setup a CI to push generated bindings to a dedicated branch

- .github/workflows/test.yml
At the time of we added `macos-11` runner, the nightly toolchain was needed. But, as of [Rust 1.49](https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html), `aarch64-apple-darwin` is tier 2 target. This pull request adds the following changes regarding to this issue:
- Use stable toolchain
- ~~Remove default target~~
- ~~Remove an workaround for duplication of the generated bindings~~
> Use stable Rust to build and test aarch64-apple-darwin 

- .github/workflows/test.yml
Fix this error.
```
rm: cannot remove 'generated_binding-macOS-11-R-release-rust-nightly/bindings-macos-x86_64-*.rs': No such file or directory
```
https://github.com/extendr/libR-sys/runs/2984489270?check_suite_focus=true#step:4:42
> Fix workaround on binding generation

- bindings/bindings-linux-x86_64-R4.1.rs
- wrapper.h
Address https://github.com/extendr/libR-sys/issues/66#issuecomment-882669880
I included `bindings/bindings-linux-x86_64-R4.1.rs` to show the diff for example. Other bindings will be updated after merging this into master.
> Include R_ext/Altrep.h

- README.md
The same fix as https://github.com/extendr/extendr/pull/245
> Fix broken crates.io badge

- README.md
- src/lib.rs
After looking at the published doc (https://docs.rs/libR-sys/0.2.2/libR_sys/), I feel these documents should be on the crate level doc, rather than the README on crates.io.
> Move documents about DEP_* envvars to crate level

- .github/workflows/test.yml
r-actions got v2 branch a month ago, and all the future improvement will be included there. So we should migrate to v2.
> Move to r-actions v2

- README.md
- build.rs
Following the discussion in #85, here I attempt to use `R_VERSION` env var to determine R version. 
I assume that `R_VERSION` will be set to something like `4.1.0`, `4.2.0-devel`, etc.
`R_VERSION` takes precedence over executing `R` to get its version to allow manual overriding through the environment variable.
> Using `R_VERSION` environement variable

- CHANGELOG.md
- README.md
- build.rs
We have added several new logics to build.rs with minimal changes. I feel now it looks fairly complex and needs to be refactored. The main changes of this pull request are the followings. The behavior of the script should stay (almost) the same.
* Currently we have two different code paths to parse the R version on envvar `LIBR_SYS_R_VERSION` and on R's output. This pull request unifies it to `parse_r_version()`.
* `probe_r_paths()` is a bit too nested. This pull request separates the logic into `get_r_home()`, `get_r_library()`, and `get_r_include()` for simplicity.
* Make the environmental variables in our convention as const and move to the top of the file so that we can discover it easier.
* Add more comments.
> Refactor build.rs

- .github/workflows/test.yml
Closes #97.
MSYS is no longer fully installed on windows-images, so we need to manually install it when necessary (mainly, MinGW toolchains).
> Configure MSYS on CI

- .github/workflows/test.yml
Use Rtools42 to see if libR-sys can work on upcoming R 4.2. Note that, at the moment, this pull request enumerates `stable-gnu` and `stable-msvc` because we don't decide which to use yet.
* Use Rtools42 (we need to specify `rtools-version` option)
* Use `use-public-rspm` option (It seems I forgot to do this in #86, sorry)
> Use Rtools42

- .github/workflows/test.yml
A small improvement to close https://github.com/extendr/libR-sys/issues/112. In terms of visibility, I think it's a good idea to set `emit-bindings` explicitly, rather than detecting `stable` implicitly because the combination is getting complex...
> Explicitly set emit-bindings: 'true'

- wrapper.h
This was done as a request from a community member. We could add all R include files and generate the entire lot of the R-api, but for now this measured approach seems the most reasonable way forward.
Disregard the PR branch name. It was a misunderstanding on my part.
> Added `R_ext/Applic.h` to the bindings.

- .cargo/config.toml
- README.md
- build.rs
- `.cargo/config.toml` can contain environment variables for all cargo-commands.
Should we use this to set `LIBRSYS_BINDINGS_OUTPUT_PATH`? I think so.
> Add a warning when output directory for generated bindings is missing

- Cargo.toml
The repository field does not seem to be set.
> Add package.repository field of Cargo.toml

- wrapper.h
This could also be useful with See extendr/extendr#474.
It will require some clever wrapping of these functions if they are to be used in Rust without a bunch of unsafe-cluttering.
> Add distribution functions

- .github/workflows/test.yml
Close #129
This pull request allows us to generate bindings on a pull request by just commenting `/bindings`. But, this works only after this gets merged into the master branch, so it's a bit difficult to test this.
> Add /bindings command

- .github/workflows/test.yml
When invoked by an issue comment event, the GitHub Action runs on the default branch, not on the branch of the pull request. So, we have to switch to the branch explicitly, but it's not available as a form of variables pre-defined by GitHub Actions ([doc](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)). I thought I solved this problem by using `r-lib/actions/pr-fetch@v2` in https://github.com/extendr/libR-sys/pull/130, but I used this only on the step **after** building the bindings.
This pull request adds the switching step also to the `test_with_bindgen` job.
> Use the branch of the pull request when /bindings

- .github/workflows/test.yml
This is a small followup of https://github.com/extendr/libR-sys/pull/134. The CI automatically update the links of the default binding for each platform when `release` is bumped to a new version of R. I just forgot this mechanism when I reviewed https://github.com/extendr/libR-sys/pull/134, sorry.
> Add linux-aarch64 to the targets of auto-update on the CI

- bindings/bindings-linux-aarch64-R4.1.rs
- bindings/bindings-linux-aarch64-R4.2.rs
- bindings/bindings-linux-aarch64-R4.3-devel.rs
- bindings/bindings-linux-x86_64-R4.1.rs
- bindings/bindings-linux-x86_64-R4.2.rs
- bindings/bindings-linux-x86_64-R4.3-devel.rs
- bindings/bindings-macos-aarch64-R4.2.rs
- bindings/bindings-macos-x86_64-R4.1.rs
- bindings/bindings-macos-x86_64-R4.2.rs
- bindings/bindings-macos-x86_64-R4.3-devel.rs
- bindings/bindings-windows-x86-R4.1.rs
- bindings/bindings-windows-x86_64-R4.1.rs
- bindings/bindings-windows-x86_64-R4.2.rs
- bindings/bindings-windows-x86_64-R4.3-devel.rs
- build.rs
Adding these lines to the `clang`-call enables getting some comments.
This is not much, but it is *something*. Maybe it will be more useful later
> Gather comments from headers

- .github/workflows/doc.yml
Close #142
This GitHub Actions is based on the official one: https://github.com/actions/starter-workflows/blob/main/pages/static.yml, which deploys using custom Action, not `gh-pages` branch. So, we have to change the following setting to "GitHub Actions".
> Deploy to GitHub Pages

- bindings/bindings-linux-aarch64-R4.3-devel.rs
- bindings/bindings-linux-x86_64-R4.3-devel.rs
- bindings/bindings-macos-x86_64-R4.3-devel.rs
- bindings/bindings-windows-x86_64-R4.3-devel.rs
- wrapper.h
Note: I chose `__attribute__((__noreturn__))` instead of `__attribute__((noreturn))` as this is suggested on the following SO.
https://stackoverflow.com/a/28556713
> Define NORET manually

- build.rs
- src/lib.rs
In continuing the effort to clean-up and smooth out libR-sys, I have found that clippy complains about these constants, and we can replace c-types with rust types by this setting.
This will need to be checked more thoroughly with extendr though.
> Use rust constants and rust types in bindgen

- build.rs
This should have happened with https://github.com/extendr/libR-sys/issues/144. 
Best source I can found on the deprecated status of `VECTOR_PTR` (except the r-source in #144), is
> (There is STRING_PTR() which is used in a handful of places in the R source; VECTOR_PTR() is a deprecated interface that now throws an error.)
in https://github.com/hadley/r-internals/blob/master/vectors.md
> Remove `VECTOR_PTR` from bindings

- .github/workflows/doc.yml
For some reason, deployment to GitHub Pages now fails.
https://github.com/extendr/libR-sys/actions/runs/5474800792
Not sure if this can solve the problem, but I just found deploy-pages action now has v2.
> Update actions/deploy-pages to v2

- .github/workflows/doc.yml
As of v1.0.9, which was released 3 weeks ago, actions/upload-pages-artifact rejects files with incorrect permission. Before that, the action kindly corrected the permission, so our CI passed with this warning:
```
Warning: mode of './target/doc/.lock' changed from 0600 (rw-------) to 0644 (rw-r--r--)
```
(<https://github.com/extendr/libR-sys/actions/runs/5113126789/jobs/9191980916#step:6:31>)
But, now, it's our job to handle these files. This pull request removes the unused file `.lock`.
See https://github.com/actions/deploy-pages/issues/188 for more details.
> Fix Documents action

- Cargo.toml
Fix https://github.com/extendr/libR-sys/issues/194
While they are code comments for R's source code, cargo considers them as Rust code because they are unfortunately indented by 4 white spaces, which means cargo tries to run doctests on the code. I think libR-sys will never introduce doctests because most of the APIs cannot run without an R session, so it's fine to disable them all.
> Skip doctest

- build.rs
- Use `cargo:warning=Warning text` to properly notify users (regular `pirntln!()` do not really work)
- Put some dead code behind `cfg` (used only for bindgen)
> Use `cargo:warning` to notify users during build time

- .github/workflows/test.yml
Fix #213 
It seems the problem is the version mismatch between `upload-artifact` action and `download-artifact` action; the former specifies `main` while the latter `v3`. Since v4 was released on December 15th, now `upload-artifact` is v4, but the `download-action` stays v3.
> Use v4 of upload/download-artifact action

- .github/workflows/test.yml
fix #220
R-devel is now using Rtools44 as default.
We are seeing failure on extendr with r-devel, and it is resolved by this.
The failure is not seen on this repository though.
Once it is merged here, an equivalent correction should happen on extendr-repo.
> fix Rtools44 #220

- Cargo.toml
Minor adjustment to #196. If the feature `layout_tests` is used, then nothing happens, unless `use-bindgen` is also included. Because layout-tests aren't included in the precomputed bindings.
Therefore, we amend `layout_tests`, such that they always include `use-bindgen`. This isn't a problem in CI, because there we use `use-bindgen` as well.
> Ensure layout-tests are present when running with `feature = layout_tests`

- bindings/bindings-linux-aarch64-R4.4-devel.rs
- bindings/bindings-linux-x86_64-R4.4-devel.rs
- bindings/bindings-macos-x86_64-R4.3.rs
- bindings/bindings-macos-x86_64-R4.4-devel.rs
- bindings/bindings-macos-x86_64-R4.5-devel.rs
- bindings/bindings-windows-x86_64-R4.4-devel.rs
Somehow, these bindings was not removed from the cached bindings. I suspect our way of detecting `devel` might have been wonky, or a git merge went awry. 
Either case, here's a potential hotfix.
> bindings: Remove remaining `Rf_isS4` and `R_altrep_Coerce_method_t` as we manually define those

- bindings/bindings-linux-aarch64-R4.2.rs
- bindings/bindings-linux-aarch64-R4.3.rs
- bindings/bindings-linux-aarch64-R4.4-devel.rs
- bindings/bindings-linux-aarch64-R4.4.rs
- bindings/bindings-linux-aarch64-R4.5-devel.rs
- bindings/bindings-linux-x86_64-R4.2.rs
- bindings/bindings-linux-x86_64-R4.3.rs
- bindings/bindings-linux-x86_64-R4.4-devel.rs
- bindings/bindings-linux-x86_64-R4.4.rs
- bindings/bindings-linux-x86_64-R4.5-devel.rs
- bindings/bindings-macos-aarch64-R4.2.rs
- bindings/bindings-macos-aarch64-R4.3.rs
- bindings/bindings-macos-aarch64-R4.4.rs
- bindings/bindings-macos-aarch64-R4.5-devel.rs
- bindings/bindings-macos-x86_64-R4.2.rs
- bindings/bindings-macos-x86_64-R4.3.rs
- bindings/bindings-macos-x86_64-R4.4-devel.rs
- bindings/bindings-macos-x86_64-R4.4.rs
- bindings/bindings-macos-x86_64-R4.5-devel.rs
- bindings/bindings-windows-x86_64-R4.2.rs
- bindings/bindings-windows-x86_64-R4.3.rs
- bindings/bindings-windows-x86_64-R4.4-devel.rs
- bindings/bindings-windows-x86_64-R4.4.rs
- bindings/bindings-windows-x86_64-R4.5-devel.rs
R-devel is actively redefining what is, and what is not public API.
This PR applies the restrictions found here https://github.com/extendr/libR-sys/pull/252#issuecomment-2200273018.
Note that we are following @yutannihilation's advice here on `PRESEEN` and `SYMVALUE`. 
We broke the CI for bindings generation, so a manual update of the binding is necessary. See #251.
> Manual update of non-API

- .github/workflows/test.yml
After https://github.com/extendr/libR-sys/pull/250, the scheduled execution of CI keep failing because it no longer emits bindings.
```
cp: cannot stat 'generated_binding-*/*.rs': No such file or directory
```
(https://github.com/extendr/libR-sys/actions/runs/10753234750/job/29822527827)
Whenever it fails (i.e. once per 3 days), GitHub emails me about the failure. I really don't know why GitHub blames me even after the HEAD commit of `master` is not mine. I know this is no one's fault, but this is quite annoying. So, I'd like to stop this by deleting the schedule. I think you can restore these lines when you get the generation of the bindings ready.
> Stop updating bindings using CI
